export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_RESPONSE = "LOGIN_USER_RESPONSE";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGIN_OTP_VERIFY_REQUEST = "LOGIN_OTP_VERIFY_REQUEST";
export const LOGIN_OTP_VERIFY_RESPONSE = "LOGIN_OTP_VERIFY_RESPONSE";
export const LOGIN_OTP_VERIFY_FAILED = "LOGIN_OTP_VERIFY_FAILED";

export const LOGIN_EMAIL_REQUEST = "LOGIN_EMAIL_REQUEST";
export const LOGIN_EMAIL_RESPONSE = "LOGIN_EMAIL_RESPONSE";
export const LOGIN_EMAIL_FAILED = "LOGIN_EMAIL_FAILED";


export const RESET_EMAIL_RESPONSE = 'RESET_EMAIL_RESPONSE';

export const CONFIRM_EMAIL_RESPONSE = 'CONFIRM_EMAIL_RESPONSE';


export const RESET_MOBILE_NUMBER = 'RESET_MOBILE_NUMBER';


export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_RESPONSE = "RESEND_OTP_RESPONSE";
export const RESEND_OTP_FAILED = "RESEND_OTP_FAILED";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_RESPONSE = "USER_DETAIL_RESPONSE";
export const USER_DETAIL_FAILED = "USER_DETAIL_FAILED";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_RESPONSE = "SIGNUP_USER_RESPONSE";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";

export const LOGOUT_USER = "LOGOUT_USER";


export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_RESPONSE = "USER_DATA_RESPONSE";
export const USER_DATA_FAILED = "USER_DATA_FAILED";

export const SHOW_SUCCESS = "SHOW_SUCCESS";
export const HIDE_SUCCESS = "HIDE_SUCCESS";
export const SHOW_ERROR = "SHOW_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_RESPONSE = "GET_USER_RESPONSE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_RESPONSE = "UPDATE_USER_RESPONSE";

export const CANCEL_USER_REQUEST = "CANCEL_USER_REQUEST";
export const CANCEL_USER_RESPONSE = "CANCEL_USER_RESPONSE";
export const CANCEL_USER_FAILED = "CANCEL_USER_FAILED";


export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_RESPONSE = "USER_UPDATE_RESPONSE";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";
