export const TEAM_NAME_RESPONSE = "TEAM_NAME_RESPONSE";

export const TEAM_DETAIL_RESPONSE = "TEAM_DETAIL_RESPONSE";

export const TEAM_IS_SUB_ORG_RESPONSE = "TEAM_IS_SUB_ORG_RESPONSE";

export const TEAM_DATES_RESPONSE = "TEAM_DATES_RESPONSE";

export const TEAM_SIZE_RESPONSE = "TEAM_SIZE_RESPONSE";


export const TEAM_NAME_BACK_RESPONSE = "TEAM_NAME_BACK_RESPONSE";

export const TEAM_DETIAL_BACK_RESPONSE = "TEAM_DETIAL_BACK_RESPONSE";

export const TEAM_SUB_ORG_BACK_RESPONSE = "TEAM_SUB_ORG_BACK_RESPONSE"
export const TEAM_DATES_BACK_RESPONSE = "TEAM_DATES_BACK_RESPONSE"
export const TEAM_SIZE_BACK_RESPONSE = "TEAM_SIZE_BACK_RESPONSE";


export const FUND_DETAIL_SAVE_REQUEST = "FUND_DETAIL_SAVE_REQUEST";
export const FUND_DETAIL_SAVE_RESPONSE = "FUND_DETAIL_SAVE_RESPONSE";
export const FUND_DETAIL_SAVE_FAILED = "FUND_DETAIL_SAVE_FAILED";

export const FUND_DETAIL_REQUEST = "FUND_DETAIL_REQUEST";
export const FUND_DETAIL_RESPONSE = "FUND_DETAIL_RESPONSE";
export const FUND_DETAIL_FAILED = "FUND_DETAIL_FAILED";


export const FUND_DETAILBY_ID_REQUEST = "FUND_DETAILBY_ID_REQUEST";
export const FUND_DETAILBY_ID_RESPONSE = "FUND_DETAILBY_ID_RESPONSE";
export const FUND_DETAILBY_ID_FAILED = "FUND_DETAILBY_ID_FAILED";


export const FUND_DELETE_REQUEST = "FUND_DELETE_REQUEST";
export const FUND_DELETE_RESPONSE = "FUND_DELETE_RESPONSE";
export const FUND_DELETE_FAILED = "FUND_DELETE_FAILED";